import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppProviders from "./AppProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <AppProviders>
          {/* Background moved outside content wrapper for visibility */}
          <div
            className="fixed inset-0 -z-10"
            style={{
              background:
                "linear-gradient(135deg, #000 50%, rgba(0,60,130,0.85) 100%)",
              filter: "blur(40px)",
              transition: "background 0.8s cubic-bezier(0.4,0,0.2,1)",
            }}
            aria-hidden="true"
          />
          <div className="pt-20 min-h-screen bg-transparent">{children}</div>
        </AppProviders>
      </body>
    </html>
  );
}