import { Geist, Geist_Mono } from "next/font/google";
import { GameProvider } from "./context/GameContext";
import "./globals.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { Toaster } from "sonner";
import NavbarWrapper from "./components/NavbarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <GameProvider>
          <NavbarWrapper />
          {/* Background moved outside content wrapper for visibility */}
          <div
            className="fixed inset-0 -z-10"
            style={{
              background: "linear-gradient(135deg, #000 50%, rgba(0,60,130,0.85) 100%)",
              filter: "blur(40px)",
              transition: "background 0.8s cubic-bezier(0.4,0,0.2,1)",
            }}
            aria-hidden="true"
          />
          {/* Add a wrapper with top padding for the navbar */}
          <div className="pt-20 min-h-screen bg-transparent">
            {children}
          </div>
          <ToastContainer
            position="top-right"
            autoClose={3000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="dark"
          />
          <Toaster position="top-center" richColors closeButton theme="dark" />
        </GameProvider>
      </body>
    </html>
  );
}